CREATE TABLE IF NOT EXISTS users (
id SERIAL NOT NULL,
email VARCHAR(255) NOT NULL,
username VARCHAR(255) NOT NULL,
"password" VARCHAR(255) NOT NULL,
profile_picture VARCHAR(255) NULL,
about VARCHAR(255) NULL,
PRIMARY KEY (user_id)
);